Fix error when both required vals missing for app-namespace-prep chart
Currently, when both required values are not provided, we see an
obscure nil interface{} pointer error:
```
Error: template: conjur-namespace-prep/templates/conjur-connect-configmap.yml:3:93: executing "conjur-namespace-prep/templates/conjur-connect-configmap.yml" at <.Values.authnK8s.name>: nil pointer evaluating interface {}.name
```

For this case, the error message should be clear that both required
values are needed:
```
Error: execution error at (conjur-namespace-prep/templates/conjur-connect-configmap.yml:3:15): Both authnK8s.namespace and authnK8s.configMap are required
```